name: CI

on:
  push:
    branches: [ main, introducing-github-ci ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential liblua5.4-dev libsystemd-dev libmxml-dev cmake

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test
        run: |
          cd build
          ./run.lua